
trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  solutionName: 'Cryptollet.sln'
  androidProject: 'Cryptollet.Android/Cryptollet.Android.csproj'

jobs:

- job: BuildAndroid
  displayName: "Build Android App"
  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solutionName)'
  - task: XamarinAndroid@1
    inputs:
      projectFile: '$(androidProject)'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(buildConfiguration)'

- job: BuildiOS
  displayName: "Build iOS App"
  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solutionName)'
  - task: XamariniOS@1
    inputs:
      solutionFile: '$(solutionName)'
      configuration: '$(buildConfiguration)'
      packageApp: false
      buildForSimulator: true
      runNugetRestore: false

- job: runTests
  displayName: 'Run unit test'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: "Cryptollet.Test/Cryptollet.Tests.csprj"
      configuration: '$(buildConfiguration)'